### PR TITLE
adding ability to manage airflow webserver key

### PR DESCRIPTION
**Pull request by ITJamie**
**Description of the change**

add ability to manage webserver key in airflow config file

**Benefits**

I have been experiencing issues with airflow workers and airflow itself not honouring the alternative way of setting this with an ENV var (AIRFLOW__WEBSERVER__SECRET_KEY). 
I confirmed this by using a mount point for /opt/bitnami/airflow/airflow.cfg to a local file i could manage. Once I set the webserver secret_key in the file i no longer had issues. However managing this file in this way long term reduces the benefits of the docker image. 

**Possible drawbacks**

None that I can see as its optional like the fernet key above it

**Applicable issues**

no open issue yet

**Additional information**

Will need to be duplicated to airflow-worker git repo also

### CODE REVIEW

**Comment by Mauraza** [comment]
Hi @ITJamie,

Thanks for the PR!!
I'm going to do some testing after that, I will update this thread.

**Comment by ITJamie** [comment]
Thanks! For now im able to work with having the files manually managed. But it would be great to get fixed.

**Comment by ITJamie** [comment]
Any update on this @Mauraza ?

**Comment by Mauraza** [comment]
Hi @ITJamie,

The next release will be available these change. Thanks for the contribution!

**Comment by ITJamie** [comment]
Will it be in all three images? Worker airflow and scheduler?

**Pull request merged**
